[package]
name = "redis-server"
version = "0.1.0"
authors = ["wwq8875 <2992395632@qq.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2.22", features = ["full"] }
bytes = "0.5.6"
memchr = "2.3.3"