[package]
name = "redis-server"
version = "0.1.0"
authors = ["wwq8875 <2992395632@qq.com>"]
edition = "2018"

[dependencies]
num_cpus = "1.10.1"
bytes = "0.4.12"
mio = "0.6.19"
byteorder = "1.3.2"
memchr = "2.2.0"

[profile.release]
debug = true
